// Generated by gencpp from file robot_msgs/RobotIns.msg
// DO NOT EDIT!


#ifndef ROBOT_MSGS_MESSAGE_ROBOTINS_H
#define ROBOT_MSGS_MESSAGE_ROBOTINS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_msgs
{
template <class ContainerAllocator>
struct RobotIns_
{
  typedef RobotIns_<ContainerAllocator> Type;

  RobotIns_()
    : header()
    , cmd(0)
    , data(0)  {
    }
  RobotIns_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cmd(0)
    , data(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _cmd_type;
  _cmd_type cmd;

   typedef uint8_t _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::robot_msgs::RobotIns_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msgs::RobotIns_<ContainerAllocator> const> ConstPtr;

}; // struct RobotIns_

typedef ::robot_msgs::RobotIns_<std::allocator<void> > RobotIns;

typedef boost::shared_ptr< ::robot_msgs::RobotIns > RobotInsPtr;
typedef boost::shared_ptr< ::robot_msgs::RobotIns const> RobotInsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msgs::RobotIns_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msgs::RobotIns_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'robot_msgs': ['/home/blue/lab/wifi_robot/robot_node/src/robot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::RobotIns_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msgs::RobotIns_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::RobotIns_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msgs::RobotIns_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::RobotIns_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msgs::RobotIns_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msgs::RobotIns_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73030e4a79c67b47cdbc699cae165639";
  }

  static const char* value(const ::robot_msgs::RobotIns_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73030e4a79c67b47ULL;
  static const uint64_t static_value2 = 0xcdbc699cae165639ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msgs::RobotIns_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msgs/RobotIns";
  }

  static const char* value(const ::robot_msgs::RobotIns_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msgs::RobotIns_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint8 cmd\n\
uint8 data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::robot_msgs::RobotIns_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msgs::RobotIns_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cmd);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotIns_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msgs::RobotIns_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msgs::RobotIns_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSGS_MESSAGE_ROBOTINS_H
